function [bt,bnd_bt]=qbutnset(bnd,qflag,delay,nom,f)
% QBUTNSET Button setup. (Utility Function)
%          QBUTNSET sets up the entire interface for the IDE programs
%          LPSHAPE and PFSHAPE.

% Author: Craig Borghesani
% 8/31/93
% Copyright (c) 2003, Terasoft, Inc.

bnd_bt = [];

lf1=0.0781;
wdt=0.0578;
ht=0.0417;
top=1-0.0625;
rt=1-wdt;

estr='on';
estr2='on';
if datenum(version('-date')) < datenum('September 15, 2014'),
    xstr=['xitcade(',int2str(f),',0);'];
else
    xstr=['xitcade(',int2str(f.Number),',0);'];
end
if any(qflag==[3,4])   % FSHAPE,DFSHAPE
 estr='off';
 estr2='off';
elseif any(qflag==[5,6]),
 estr2='off';
end

AccStr = '';
if strncmp(computer,'PC',2),
   AccStr = '&';
end

% create uimenus
qfile=uimenu('label',[AccStr,'File']);
s_qfile(1)=uimenu(qfile,'label',[AccStr,'Open...'],...
                        'callback','cntopen(1)');
s_qfile(2)=uimenu(qfile,'label',[AccStr,'Save...'],...
                        'callback','cntsave(1)');
s_qfile(3)=uimenu(qfile,'label','Quick Open',...
                        'callback','cntopen(2)',...
                        'vis','off');
s_qfile(4)=uimenu(qfile,'label','Quick Save',...
                        'callback','cntsave(2)',...
                        'vis','off');
uimenu(qfile,'label',[AccStr,'Import...'],...
                        'callback','wkstoenv(''Setup'')',...
                        'separator','on');

s_qfile(5)=uimenu(qfile,'label',[AccStr,'Export...'],...
                        'callback','envtowks(''Setup'')');
%%%%%% V1.1 addition
uimenu(qfile,'label',[AccStr,'Print to Figure'],....
             'callback','qprint(''Print'')',...
             'separator','on');
%%%%%%
s_qfile(6)=uimenu(qfile,'label',['E',AccStr,'xit'],...
                        'callback',xstr,...
                        'separator','on');

qdes=uimenu('label','Design',...
            'vis','off');
s_qdes(1)=uimenu(qdes,'label','UnDo',...
                      'callback','qundoit');
s_qdes(2)=uimenu(qdes,'label','Add via Numeric...',...
                      'separator','on',...
                      'callback','qaddelmt(0)');
s_qdes(3)=uimenu(qdes,'label','Add via Graphic');
ss_qdes(1)=uimenu(s_qdes(3),'label','Gain',...
                            'callback','qscrelmt(1)');
ss_qdes(2)=uimenu(s_qdes(3),'label','First Order',...
                            'callback','qscrelmt(2)');
ss_qdes(3)=uimenu(s_qdes(3),'label','Second Order',...
                            'callback','qscrelmt(3)');
ss_qdes(4)=uimenu(s_qdes(3),'label','Lead/Lag',...
                            'callback','qscrelmt(4)',...
                            'enable',estr);
ss_qdes(5)=uimenu(s_qdes(3),'label','Notch',...
                            'callback','qscrelmt(5)');
ss_qdes(6)=uimenu(s_qdes(3),'label','2/2',...
                            'callback','qscrelmt(6)',...
                            'enable',estr2);
s_qdes(4)=uimenu(qdes,'label','Delete...',...
                      'callback','qdelelmt(0)');
s_qdes(5)=uimenu(qdes,'label','Edit...',...
                      'callback','qedtelmt(0,0)');
s_qdes(6)=uimenu(qdes,'label','Iterate...',...
                      'callback','qitrelmt(0,0)');

qview=uimenu('label',[AccStr,'View']);
uimenu(qview,'label',[AccStr,'Zoom'],...
             'callback','qcadevuw(17)',...
             'checked','off',...
             'tag','zoommode');
s_qview(1)=uimenu(qview,'label',[AccStr,'Full'],...
                        'callback','qcadevuw(1)',...
                        'separator','on');
s_qview(2)=uimenu(qview,'label',[AccStr,'In'],...
                        'callback','qcadevuw(2)','vis','off');
s_qview(3)=uimenu(qview,'label',[AccStr,'Out'],...
                        'callback','qcadevuw(3)','vis','off');
s_qview(4)=uimenu(qview,'label',[AccStr,'Last'],...
                        'callback','qcadevuw(4)','vis','off');
s_qview(5)=uimenu(qview,'label',[AccStr,'Move'],...
                        'callback','qcadevuw(11)',...
                        'separator','on','vis','off');
s_qview(6)=uimenu(qview,'label',[AccStr,'Zoom'],...
                        'callback','qcadevuw(13)','vis','off');
s_qview(7)=uimenu(qview,'label',[AccStr,'Axis...'],...
                        'callback','qaxschng(''Setup'')');
uimenu(qview,'label',[AccStr,'Nichols Grid'],...
                        'callback','qcadevuw(16)',...
                        'enable',estr,...
                        'separator','on');

qtools=uimenu('label',[AccStr,'Tools']);
s_qtools(1)=uimenu(qtools,'label','Elements',...
                          'callback','qcadevuw(9)',...
                          'vis','off');
s_qtools(2)=uimenu(qtools,'label',[AccStr,'Plant'],...
                          'callback','qcadevuw(14)');
s_qtools(3)=uimenu(qtools,'label','Reduction...',...
                          'separator','on',...
                          'callback','qmodlred(0)',...
                          'vis','off');
s_qtools(4)=uimenu(qtools,'label','Conversion...',...
                          'callback','cntcnvt(0)',...
                          'enable',estr,...
                          'vis','off');
junk1 = uimenu(qtools,'label',[AccStr,'Discretize...'],...
                      'callback','qcntdisc(''Setup'')',...
                      'separator','on');
junk2 = uimenu(qtools,'label',[AccStr,'Auto-Shape...'],...
                      'callback','qautoshp(''Setup'')',...
                      'vis','off');
junk3 = uimenu(qtools,'label','Stabilizing Beta...',...
                      'callback','qstabeta(0)',...
                      'vis','off');

s_qtools(5)=uimenu(qtools,'label',[AccStr,'Stability'],...
                          'separator','on',...
                          'callback','qcadevuw(8)',...
                          'enable',estr);
s_qtools(6)=uimenu(qtools,'label',[AccStr,'Frequency...'],...
                          'callback','qfrqchng(''Setup'')',...
                          'enable',estr);
uimenu(qtools,'label',[AccStr,'Bode Plots...'],...
                      'callback','qbodeplot;');
s_qtools(7)=uimenu(qtools,'label',['S',AccStr,'tore'],...
                          'callback','cntstor',...
                          'separator','on',...
                          'tag','Store');
s_qtools(8)=uimenu(qtools,'label',[AccStr,'Recall'],...
                          'callback','cntrecl',...
                          'enable','off',...
                          'tag','Recall');

if any(qflag==[2,4,6]),
   set([junk1, junk2, junk3],'enable','off');
   set(s_qtools(3),'enable','off');
end

if isa(nom, 'frd') | qflag > 2,
   set(s_qtools(2),'enable','off');
end

if delay~=0 | (isa(nom, 'frd')),
   set(s_qtools(5),'enable','off');
   if isa(nom, 'frd'),
      set(s_qtools(6),'enable','off');
   end
end

bt=[qfile,s_qfile,qdes,s_qdes,ss_qdes,qview,s_qview,qtools,s_qtools, junk2, junk1, junk3];

help=uimenu('label',[AccStr,'Help'],'vis','off');
uimenu(help,'label',[AccStr,'File'],...
            'callback','helpdlg(''qfile.hlp'',''QFile Help'');');
uimenu(help,'label',[AccStr,'Design'],...
            'callback','helpdlg(''qdesign.hlp'',''QDesign Help'');');
uimenu(help,'label',[AccStr,'View'],...
            'callback','helpdlg(''qview.hlp'',''QView Help'');');
uimenu(help,'label',[AccStr,'Tools'],...
            'callback','helpdlg(''qtools.hlp'',''QTools Help'');');

% set up buttons for toggling bounds from visible to invisible
ct=1;
cvec=['r';'g';'b';'c';'m'];
clr=[cvec;cvec;cvec;cvec];
clr=[clr;clr;clr;clr;clr];
clr=[clr;clr;clr;clr;clr];
[rb,cb]=size(bnd);
bnd_bt={};
if rb,
   ow=bnd(rb,:); ow=sort(ow); ow(find(diff(ow)==0))=[];
   tp=top-ht;
   for t=1:length(ow),
      wstr=sprintf('%-0.4g',ow(t));
      loc=find(wstr=='e');
      if length(loc),
         wstr(find(wstr(loc:length(wstr))=='0')+(loc-1))=[];
      else
         wstr(find(wstr==' '))=[];
      end
      st=[wstr,',',clr(t),' (on)'];
      bnddata=bnd(1:(rb-1),find(ow(t)==bnd(rb,:)));
      bnd_bt(ct,1:2)={st, bnddata};
      tp=tp-ht;
      ct=ct+1;
   end
end
%set(f,'toolbar','figure');
