function qfttool(HardwareName)
% QFTTOOL Digital Signal Analyzer.

% Author: Craig Borghesani <cborg@terasoft.com>
% Date: 1/22/02 3:52PM

QFTToolFigure = findobj(allchild(0),'type','figure','tag','QFTtool');
if ~isempty(QFTToolFigure),
   figure(QFTToolFigure);
   return;
end

% define various shades of grey
grey = get(0,'defaultuicontrolbackground');
ltgrey = [0.5,0.5,0.5]*1.5;
dkgrey = [0.5,0.5,0.5]*0.5;

% compute center of screen
ScreenSize     = get(0,'screensize');
FigureWidth    = ScreenSize(3) - 100;
FigureHeight   = ScreenSize(4) - 100;
FigureLeft     = (ScreenSize(3) - FigureWidth)/2;
FigureBottom   = (ScreenSize(4) - (FigureHeight+20))/2;
FigurePosition = [FigureLeft, FigureBottom, FigureWidth, FigureHeight];

% create main screen figure object
QFTToolFigure = figure('position',FigurePosition,...
                       'name','QFT Tool',...
                       'menubar','none',...
                       'numbertitle','off',...
                       'visible','off',...
                       'tag','QFTtool',...
                       'backingstore','off',...
                       'doublebuffer','on',...
                       'defaultuicontrolbackgroundcolor',grey,...
											 'resizefcn','qfttoolresizefcn;');

% determine frame sizes depending upon figure size
BorderWidth = 5;
SectionBorderWidth = 3;
MainFrameWidth = 225;
MainFramePosition = [FigureWidth - (MainFrameWidth + 5), ...
                     5, ...
                     MainFrameWidth, ...
                     FigureHeight-10];
SubFramePosition = [MainFramePosition(1) + BorderWidth, ...
                    MainFramePosition(2) + BorderWidth, ...
                    MainFramePosition(3) - 2*BorderWidth, ...
                    FigureHeight - 2*BorderWidth];

SubFrame1Height = 50;
SubFrame2Height = (SubFramePosition(4) - SubFrame1Height) * 0.67 - 4*BorderWidth;
SubFrame3Height = (SubFramePosition(4) - SubFrame1Height) * 0.33 - 4*BorderWidth;

SubFrame1Position = [SubFramePosition(1), ...
                     MainFramePosition(4) - (SubFrame1Height + 5), ...
                     SubFramePosition(3), ...
                     SubFrame1Height];
SubFrame1UILeft   = SubFrame1Position(1) + BorderWidth;
SubFrame1UIBottom = sum(SubFrame1Position([2,4])) - 10;

SubFrame2Position = [SubFramePosition(1), ...
                     SubFrame1Position(2) - (SubFrame2Height + 10), ...
                     SubFramePosition(3), ...
                     SubFrame2Height];
SubFrame2UILeft   = SubFrame2Position(1) + BorderWidth;
SubFrame2UIBottom = sum(SubFrame2Position([2,4])) - 10;

SubFrame3Position = [SubFramePosition(1), ...
                     SubFrame2Position(2) - (SubFrame3Height + 10), ...
                     SubFramePosition(3), ...
                     SubFrame3Height];
SubFrame3UILeft   = SubFrame3Position(1) + BorderWidth;
SubFrame3UIBottom = sum(SubFrame3Position([2,4])) - 10;

FullWidth         = SubFramePosition(3) - 2*BorderWidth;
HalfWidth         = FullWidth/2 - BorderWidth/2;
ThirdWidth        = FullWidth/3 - (BorderWidth*2)/3;

StatusBarPos = [5 + BorderWidth, ...
                10, ...
                FigureWidth - 2 * (5 + BorderWidth), ...
                20];

%%% Control panel for controller design
QFTToolData.Frame = uicontrol('style','push',...
                              'pos',MainFramePosition,...
                              'enable','off');

%% Pointer Information (subframe 1)
QFTToolData.Mouse(1) = uicontrol('style','frame',...
                                 'pos',SubFrame1Position,...
                                 'fore','k');
QFTToolData.Mouse(2) = uicontrol('style','text',...
                                 'pos',[SubFrame1UILeft, SubFrame1UIBottom, 100, 17],...
                                 'string',' Pointer Info',...
                                 'horiz','left');

%% Controller design (subframe 2)
QFTToolData.Elements(1) = uicontrol('style','frame',...
                                  'pos',SubFrame2Position,...
                                  'fore','k');
QFTToolData.Elements(2) = uicontrol('style','text',...
                                  'pos',[SubFrame2UILeft, SubFrame2UIBottom, 100, 17],...
                                  'string',' Elements',...
                                  'horiz','left');

SubFrame2UIBottom = SubFrame2UIBottom - 20;
QFTToolData.Elements(3) = uicontrol('style','popup',...
                                  'pos',[SubFrame2UILeft, SubFrame2UIBottom, FullWidth, 20],...
                                  'string',{'Real Pole', ...
																	          'Real Zero', ...
																						'Complex Pole', ...
																						'Complex Zero', ...
																						'Super 2nd (2/2)', ...
																						'Integrator/Differentiator', ...
																						'Lead or Lag', ...
																						'Notch'},...
                                  'callback','',...
																	'back','w',...
                                  'horiz','left',...
                                  'value',1);

SubFrame2UIBottom = SubFrame2UIBottom - 20;
QFTToolData.Elements(4) = uicontrol('style','text',...
                                  'pos',[SubFrame2UILeft, SubFrame2UIBottom, ThirdWidth, 15],...
                                  'string','Pole',...
                                  'horiz','left');
QFTToolData.Elements(5) = uicontrol('style','text',...
                                  'pos',[SubFrame2UILeft+ThirdWidth+5, SubFrame2UIBottom, ThirdWidth, 15],...
                                  'string','Pole',...
                                  'horiz','left');
QFTToolData.Elements(6) = uicontrol('style','text',...
                                  'pos',[SubFrame2UILeft+ThirdWidth*2+5*2, SubFrame2UIBottom, ThirdWidth, 15],...
                                  'string','Pole',...
                                  'horiz','left');

SubFrame2UIBottom = SubFrame2UIBottom - 20;
QFTToolData.Elements(7) = uicontrol('style','edit',...
                                  'pos',[SubFrame2UILeft, SubFrame2UIBottom, ThirdWidth, 20],...
                                  'string','',...
																	'back','w',...
                                  'horiz','right');
QFTToolData.Elements(8) = uicontrol('style','edit',...
                                  'pos',[SubFrame2UILeft+ThirdWidth+5, SubFrame2UIBottom, ThirdWidth, 20],...
                                  'string','',...
																	'back','w',...
                                  'horiz','right');
QFTToolData.Elements(9) = uicontrol('style','edit',...
                                  'pos',[SubFrame2UILeft+ThirdWidth*2+5*2, SubFrame2UIBottom, ThirdWidth, 20],...
                                  'string','',...
																	'back','w',...
                                  'horiz','right');

SubFrame2UIBottom = SubFrame2UIBottom - 25;
QFTToolData.Elements(10) = uicontrol('style','push',...
                                  'pos',[SubFrame2UILeft, SubFrame2UIBottom, HalfWidth, 20],...
                                  'string','Add');
QFTToolData.Elements(11) = uicontrol('style','push',...
                                  'pos',[SubFrame2UILeft+HalfWidth+5, SubFrame2UIBottom, HalfWidth, 20],...
                                  'string','Delete');

SubFrame2UIBottom = SubFrame2UIBottom - 25;
QFTToolData.Elements(12) = uicontrol('style','push',...
                                  'pos',[SubFrame2UILeft, SubFrame2UIBottom, FullWidth, 20],...
                                  'string','Add using Mouse');

ListboxBottom = SubFrame2Position(2) + 30;
ListboxHeight = (SubFrame2UIBottom - 5) - ListboxBottom;
QFTToolData.Elements(13) = uicontrol('style','listbox',...
                                  'pos',[SubFrame2UILeft, ListboxBottom, FullWidth, ListboxHeight],...
																	'back','w',...
                                  'string','');

SubFrame2UIBottom = SubFrame2Position(2) + 5;
QFTToolData.Elements(14) = uicontrol('style','push',...
                                  'pos',[SubFrame2UILeft, SubFrame2UIBottom, HalfWidth, 20],...
                                  'string','Reduce');
QFTToolData.Elements(15) = uicontrol('style','push',...
                                  'pos',[SubFrame2UILeft+HalfWidth+5, SubFrame2UIBottom, HalfWidth, 20],...
                                  'string','Convert');

%% Bound (subframe 3)
QFTToolData.Bounds(1) = uicontrol('style','frame',...
                                  'pos',SubFrame3Position,...
                                  'fore','k');
QFTToolData.Bounds(2) = uicontrol('style','text',...
                                  'pos',[SubFrame3UILeft, SubFrame3UIBottom, 100, 17],...
                                  'string',' Bounds',...
                                  'callback','qftcallbacks(''Trace 2'')',...
                                  'horiz','left');

ListboxBottom = SubFrame3Position(2) + 30;
ListboxHeight = (SubFrame3UIBottom) - ListboxBottom;
QFTToolData.Bounds(1) = uicontrol('style','listbox',...
                                  'pos',[SubFrame3UILeft, ListboxBottom, FullWidth, ListboxHeight],...
																	'back','w',...
                                  'string','');

SubFrame3UIBottom = SubFrame3Position(2) + 5;
QFTToolData.Elements(2) = uicontrol('style','push',...
                                  'pos',[SubFrame3UILeft, SubFrame3UIBottom, ThirdWidth, 20],...
                                  'string','Hide');
QFTToolData.Elements(3) = uicontrol('style','push',...
                                  'pos',[SubFrame3UILeft+ThirdWidth+5, SubFrame3UIBottom, ThirdWidth, 20],...
                                  'string','Hide All');
QFTToolData.Elements(4) = uicontrol('style','push',...
                                  'pos',[SubFrame3UILeft+ThirdWidth*2+5*2, SubFrame3UIBottom, ThirdWidth, 20],...
                                  'string','Reset');

set(QFTToolFigure,'userdata',QFTToolData);

drawnow;

set(QFTToolFigure,'vis','on',...
                  'handlevisibility','callback');
